version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest-browsers

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install dependencies
          command: npm install


      # Builds, tests and checks
      - run: 
          name: Build application
          command: npm run build

      - run:
          name: Install local server dependencies
          command: npm install --no-save http-server

      - run:
          name: Start local server
          command: node_modules/.bin/http-server ./public
          background: true

      - run:
          name: Run lighthouse tests
          command: sleep 5 && npm run check:perf

      - run:
          name: Send stats to MoM
          command: npm install --no-save mom-agent && node_modules/.bin/mom-agent

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      - store_artifacts:
          path: ./stats
          destination: stats
